---
title: "Merge DFs"
author: "Laurits & Idun"
date: "2023-11-06"
output: html_document
---

```{r}
pacman::p_load(tidyverse)
```


```{r}
metadata <- read_csv(file = "../Data/Cleaned_USA.csv", )
semantics <- read_csv(file = "../Data/Lexcial_information/SEMANTIC_time_1.csv")
phonological <- read_csv(file = "../Data/Lexcial_information/PHONETIC_time_1.csv")
word_length <- read_csv(file = "../Data/Lexcial_information/WORD_LENGTH_time_1.csv")

```

# Rename value
```{r}
semantics <- semantics %>% 
    rename(Semantic_centrality = value) %>% 
    select(Child_ID,
           item_definition,
           Semantic_centrality)

phonological <- phonological %>% 
    rename(Phonological_centrality = value) %>% 
    select(Child_ID, 
           item_definition, 
           Phonological_centrality)

word_length <- word_length %>% 
    rename(Word_length_centrality = value) %>% 
    select(Child_ID, 
           item_definition, 
           Word_length_centrality)

metadata <- metadata %>% 
    rename(Child_ID = child_id,
           Knows_Word = value) %>% 
    select(Child_ID, 
           age, 
           item_definition, 
           Knows_Word,birth_order, 
           caregiver_education, 
           sex)



```

# Merge that shit
```{r}
Centrality_DF <- merge(x = semantics, y = phonological, by = c("Child_ID", "item_definition"))
Centrality_DF <- merge(x = Centrality_DF, y = word_length, by = c("Child_ID", "item_definition"))
Centrality_DF <- merge(x = Centrality_DF, y = metadata, by = c("Child_ID", "item_definition"))


rm(phonological, semantics, word_length)
```


# Adding time point column 
```{r}
Timepoint_data <- Centrality_DF %>% 
    group_by(Child_ID) %>% 
    distinct(age)%>%
    arrange(Child_ID, age)%>%
    mutate(Timepoint = rank(age))

Centrality_DF <- merge(x = Centrality_DF, y = Timepoint_data, by = c("Child_ID", "age"))





#' Save age and caregiver_education as ordered factor
education_levels<- c("Some Secondary", "Secondary", "Some College", "College", "Some Graduate", "Graduate")
Centrality_DF <- Centrality_DF %>% 
    mutate(age = factor(age,
                        ordered = TRUE, 
                        levels = sort(unique(age))),
           caregiver_education = factor(caregiver_education,
                                        ordered = TRUE,
                                        levels = education_levels))
```

# Simplyfying the data by assuming that all words learned at t1 will also be learned at t2 (even though there are exceptions)
```{r}
#Only interested in t1 and t2 for now
Centrality_DF <- Centrality_DF %>% 
    filter(Timepoint == 1 | Timepoint == 2)

# First, create a data frame of known words at timepoint 1
known_at_timepoint_1 <- Centrality_DF %>%
  filter(Timepoint == 1 & Knows_Word == 1) %>%
  select(Child_ID, item_definition) # Keep only the necessary columns

# Making sure there are no duplicates
known_at_timepoint_1 <- known_at_timepoint_1 %>%
  distinct(Child_ID, item_definition, .keep_all = TRUE)

# Create a data frame of known words at timepoint 2
known_at_timepoint_2 <- Centrality_DF %>%
  filter(Timepoint == 2 & Knows_Word == 1) %>%
  select(Child_ID, item_definition) # Keep only the necessary columns

# Making sure there are no duplicates
known_at_timepoint_2 <- known_at_timepoint_2 %>%
  distinct(Child_ID, item_definition, .keep_all = TRUE)

# Figuring out which words are known at t1 but not at t2 so we can check if it works later on
words_known_at_1_not_at_2 <- anti_join(known_at_timepoint_1, known_at_timepoint_2, 
                                       by = c("Child_ID", "item_definition"))

# Overwriting t2 to knows_word = 1 when word is known at t1 
Centrality_DF <- Centrality_DF %>% 
  left_join(known_at_timepoint_1 %>% 
              select(Child_ID, item_definition) %>% 
              mutate(Knows_Word_at_2 = 1), by = c("Child_ID", "item_definition")) %>%
  mutate(Knows_Word = ifelse(Timepoint == 2 & !is.na(Knows_Word_at_2), 1, Knows_Word)) %>%
  select(-Knows_Word_at_2) # Removing the helper column

```


```{r}
write_csv(x = Centrality_DF,file = "../Data/Cleaned/CENTRALITY_DF.csv")
```

# Investigating how age is distributed
```{r}

t1 <- Centrality_DF %>% 
    filter(Timepoint == 1) %>% 
    mutate(age = as.numeric(age))

t2 <- Centrality_DF %>% 
    filter(Timepoint == 2) %>% 
    mutate(age = as.numeric(age))

hist(t1$age)
hist(t2$age)
```
















