---
title: "wordbank"
author: "Tilde Sloth & Laurits ;-)))"
date: "2023-09-18"
output: html_document
---
# CLEANING DATASET
## Loading packages
```{r}
pacman::p_load(ggplot2, tidyverse, rethinking, stringr)
```


## Loading data
```{r}
worddata_usa <- read_csv("../Data/wordbank_instrument_data_us.csv")
childdata_usa <- read_csv("../Data/wordbank_administration_data_us.csv")

#creating a list of all the children that have longitudinal data
specialkids <- worddata_usa %>%
    group_by(child_id)%>%
    filter(n_distinct(age) > 1)%>%
    distinct(child_id)

#making a subset of all the children that have longitudinal data
longitudinal_usa <- worddata_usa %>%
  group_by(child_id) %>%
  filter(n_distinct(age) > 1) %>%
  ungroup()

```

## Merging data
```{r}
data_usa <- merge(longitudinal_usa, childdata_usa, by = c("child_id","age")) #important that you put the columns in a vector
```

## Cleaning data
```{r}
#only looking at words
data_usa <- data_usa %>%
  filter(item_kind == "word")

#removing words that are sounds
data_usa <- data_usa %>%
  filter(category != "sounds")

#removing unimportant columns
data_usa <- subset(data_usa, select = -c(downloaded.x, downloaded.y, is_norming, ethnicity, race, birth_weight, born_early_or_late, gestational_age, zygosity, language_exposures, health_conditions, monolingual, typically_developing))

#looking at the unique "more than one words"
more_than_one_word <- data_usa[str_detect(data_usa$item_definition, "\\s+"), ]

more_than_one_word_unique <- more_than_one_word %>% distinct(item_definition)

#removing words that are two words
data_usa <- data_usa %>%
  mutate(item_definition = gsub(" \\(.*", "", item_definition)) %>%
  filter(!grepl(" ", item_definition) | grepl(" \\(", item_definition))
 
data_usa <- data_usa %>%
  mutate(uni_lemma = gsub(" \\(.*", "", uni_lemma)) %>%
  filter(!grepl(" ", uni_lemma) | grepl(" \\(", uni_lemma))
 
data_usa <- data_usa %>%
  mutate(english_gloss = gsub(" \\(.*", "", english_gloss)) %>%
  filter(!grepl(" ", english_gloss) | grepl(" \\(", english_gloss))

#remove words that end with *
data_usa <- data_usa %>% 
  # Remove the * character from words that end with it
  mutate(item_definition = str_remove(item_definition, "\\*$"))

#change words with /
data_usa <- data_usa %>%
  # Remove everything after the /
  mutate(item_definition = str_remove_all(item_definition, "/.*"))

#changing item_id column
data_usa$item_id <- substr(data_usa$item_id, start = 6, stop = nchar(data_usa$item_id))

data_usa <- data_usa %>% 
    mutate(item_id = as.numeric(item_id))

```


## Dummy variables 
```{r}
#checking unique values
unique(data_usa$value)

#replacing NA with 0 and "produces" with 1
data_usa$value <- ifelse(data_usa$value != "produces", 0, 1)

data_usa$value[is.na(data_usa$value)] <- 0

print(data_usa$value)
```
## Investigating duplicate items
```{r}
#unique words
length(unique(data_usa$item_definition))
#618 words

length(unique(subsetdata_usa$item_definition))
#618 words

#creating a list of words
child1_words <- as.list(child1_16$item_definition)

length(child1_words) #list is 630 hmm (should be 618)

#looking for duplicates
sum(duplicated(child1_words)) #12 duplicates

duplicated(child1_words) #we figure out that there are two inputs for some words (eg chicken with category = animal and chicken with category = food)

```

### Removing duplicate items
```{r}

child1_16 %>% 
    group_by(item_definition) %>% 
    filter(n() > 1) %>% 
    ungroup %>% 
    arrange(item_definition)

items_to_remove = c(220, 23, 412, 421, 424, 30, 129, 477, 486, 260, 154, 502)

for (i in items_to_remove){
    data_usa <- subset(data_usa, item_id != i)
}

```


## Making a smaller subset of data to work with
```{r}
subsetdata_usa <- data_usa %>% 
    filter(child_id < 1600) # This is only 75 kids btw

# Save subset as csv for import in other files
write.csv(subsetdata_usa, file = "../Data/75kidsubset.csv")

```

## Investigating data
```{r}
#rethinking::precis(subsetdata_usa)

#looking at one child

child1 <- data_usa %>% 
    filter(child_id == 1416)

child1_16 <- child1 %>% 
    filter(age == 16)

child1 %>% 
    filter(age == 22)
```


